# -*- coding: utf-8 -*-
"""Torre de Hanoi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-d5ubMzK3LlMNMV-QOVpaJ-B_XmqAG7
"""

def mover_disco(inicio,fim):
    print("Mova o disco de",inicio,"para",fim)

def mover_torre(disco,partida, chegada, intermediario):
  if disco == 1:
    # Move o disco e finaliza a função
    mover_disco(partida,chegada)
  else:
      mover_torre(disco-1,partida,intermediario,chegada)
      mover_disco(partida,chegada)
      mover_torre(disco-1,intermediario,chegada,partida)


mover_torre(1,"A","B","C")